package cab302.iirtt.assignment1.model;

import java.util.List;

public class AdviceTip extends AIResponse {
    /**
     * Default Constructor of AdviceTop Class
     */
    public AdviceTip() {

    }
    /**
     * Declares a FortuneCookie AIResponse
     * @param responseRating The rating of the response
     * @param responseDate The date of which the response was generated
     * @param responseText The response generated by the AI
     * @param userInput The prompt by the User
     * @param favourite If the User favourite it
     * @param userID The User ID of the User who generated the response
     */
    public AdviceTip(int responseRating, String responseDate, String responseText, String userInput, boolean favourite, int userID) {
        super(AIResponse.ResponseType.valueOf("ADVICE_TIP"), responseRating, responseDate, responseText, userInput, favourite, userID);
    }

    @Override
    public void generateResponse(String userInput) {
        // TODO: Creates an advice/tip AI response using uploaded material
    }

    @Override
    public List<AIResponse> viewResponses(String userID) { // maybe
        // TODO: Returns a list of all AdviceTip AI responses with the same UserID
        return null;
    }
}
