package cab302.iirtt.assignment1.model;

import java.util.List;

public class FunPrediction extends AIResponse {
    /**
     * Declares a FortuneCookie AIResponse
     * @param responseRating The rating of the response
     * @param responseDate The date of which the response was generated
     * @param responseText The response generated by the AI
     * @param userInput The prompt by the User
     * @param favourite If the User favourite it
     * @param userID The User ID of the User who generated the response
     */
    public FunPrediction(int responseRating, String responseDate, String responseText, String userInput, boolean favourite, int userID) {
        super(AIResponse.ResponseType.valueOf("FUN_PREDICTION"), responseRating, responseDate, responseText, userInput, favourite, userID);
    }

    @Override
    public void generateResponse(String userInput, String responseType, String mood) {
        // TODO: Creates a fun prediction AI response
    }

    @Override
    public List<AIResponse> viewResponses(String userID) { // maybe
        // TODO: Returns a list of all fun predictions AI responses with the same UserID
        return null;
    }
}
