package cab302.iirtt.assignment1.model;

import cab302.iirtt.assignment1.MainApplication;

import java.time.LocalDate;
import java.util.List;

public class FunPrediction extends AIResponse {
    /**
     * Default Constructor of FunPrediction Class
     */
    public FunPrediction() {

    }
    /**
     * Declares a FortuneCookie AIResponse
     * @param responseRating The rating of the response
     * @param responseDate The date of which the response was generated
     * @param responseText The response generated by the AI
     * @param userInput The prompt by the User
     * @param favourite If the User favourite it
     * @param userID The User ID of the User who generated the response
     */
    public FunPrediction(int responseRating, String responseDate, String responseText, String userInput, boolean favourite, int userID) {
        super(AIResponse.ResponseType.valueOf("FUN_PREDICTION"), responseRating, responseDate, responseText, userInput, favourite, userID);
    }

    @Override
    public void generateResponse(String userInput) {
        if (MainApplication.currentUser == null) {
            System.out.println("Error, User is not Logged-in to an account");
            return;
        }
        userInput = "Generate a fun prediction for a " + MainApplication.currentUser.getMood() + "  student. Please make it less than 30 words.";
        AIResponseDAO aiResponseDAO = new AIResponseDAO();
        GeminiAPI geminiAPI = new GeminiAPI();
        String generatedResponse = geminiAPI.run(userInput);
        FunPrediction funPrediction = new FunPrediction(0, LocalDate.now().toString(), generatedResponse, userInput, false, MainApplication.currentUser.getUserID());
        aiResponseDAO.addAIResponse(funPrediction);
    }

    @Override
    public List<AIResponse> viewResponses(String userID) { // maybe
        // TODO: Returns a list of all fun predictions AI responses with the same UserID
        return null;
    }
}
